# Configuration for HERMES workflow to publish this software to Zenodo Sandbox
# See also docs at https://docs.software-metadata.pub for more info.

[harvest]
sources = [ "cff" ]

[harvest.cff]
enable_validation = false

[deposit]
target = "invenio_rdm"

[deposit.invenio_rdm]
site_url = "https://sandbox.zenodo.org"
access_right = "open"

[postprocess]
execute = [ "config_record_id" ]
