[harvest]
from = [ "cff", "git",]

[deposit]
mapping = "invenio"
target = "invenio"

[post]
process = [ "config_record_id",]

[harvest.cff]
validate = false

[deposit.invenio]
site_url = "https://sandbox.zenodo.org"
access_right = "open"
record_id = 1202585
