# Configuration for HERMES workflow to publish this software to Zenodo Sandbox
# See also docs at https://docs.software-metadata.pub for more info.

[harvest]
from = [ "git", "cff" ]

[harvest.cff]
validate = false

[deposit]
target = "invenio"

[deposit.invenio]
site_url = "https://sandbox.zenodo.org"
access_right = "open"

[postprocess]
execute = [ "config_record_id" ]
