name: Software Publication

on:
  push:
    # You will want to include this in your project, targeting your stable branch to avoid unnecessary runs
    # in feature branches.
    # branches:
    #   - main
  pull_request:
    types:
      - closed

jobs:
  hermes-prepare:
    name: Prepare Metadata for Curation
    runs-on: ubuntu-latest
    # This condition becomes much easier when we only react to push events on the release branch.
    # We still need to exclude the merge commit push of the post processing PR
    if: >
      github.event_name == 'push' && ! (
        startsWith(github.ref_name, 'hermes/') ||
        contains(github.event.head_commit.message, 'hermes/post')
      )

    permissions:
      contents: write # Allow creation of new branches
      pull-requests: write # Postprocessing should be able to create a pull request with changes

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install git+https://github.com/hermes-hmc/workflow.git@testing
      - run: hermes # harvest + process
      - run: hermes curate

      - run: |      
          # Cache current branch for PR close job 
          git branch --show-current > .hermes/curate/target_branch
          
          # Shorten the SHA for the PR title
          SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c -8)
          echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"
          
          # Create a curation branch
          git branch -c "hermes/curate-$SHORT_SHA"
          git push origin "hermes/curate-$SHORT_SHA"
          
          # Explicitly add to-be-curated metadata (which is ignored via .gitignore!)
          git add -f .hermes/curate
      - uses: peter-evans/create-pull-request@v4
        with:
          base: hermes/curate-${{ github.run_id }}
          branch: hermes/curate-result-${{ env.SHORT_SHA }}
          title: Metadata Curation for Commit ${{ env.SHORT_SHA }}
          body: |
            Please carefully review the attached metadata.
            If you are satisfied with the result, you may merge this PR, which will trigger deposition.
            (Any temporary branches will be cleaned up.)
          delete-branch: true

  hermes-curate:
    name: Publish Software with Curated Metadata
    if: github.event.pull_request.merged == true && startsWith( github.base_ref , 'hermes/curate-')

    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow creation of new branches
      pull-requests: write # Postprocessing should be able to create a pull request with changes

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install git+https://github.com/hermes-hmc/workflow.git@testing

      # Export your artifacts (in some way, might need adaption to your project)
      - run: git archive --format zip HEAD src > showcase.zip

      # Run the HERMES deposition and postprocessing steps.
      - run: hermes deposit --initial --auth-token ${{ secrets.ZENODO_SANDBOX }} --file showcase.zip --file README.md
      - run: hermes postprocess

      # Note 1: We change the base branch here for the PR. This flow runs so far within the "curated-metadata-*" branch,
      #         but now we want to add the changes done by deposit and post processing to the branch that was initially
      #         said to be published using HERMES.
      # Note 2: The c-r-p action will NOT inherit the commits we did in the previous job. It will only look at the
      #         changes within this local workspace we did *now*.
      - run: echo "TARGET_BRANCH=$(cat .hermes/curate/target_branch)" >> "$GITHUB_ENV"
      - uses: peter-evans/create-pull-request@v4
        with:
          branch: hermes/post-${{ github.run_id }}
          base: ${{ env.TARGET_BRANCH }}
          title: Review hermes post-processing results
          body: |
            This is an automated pull request created by HERMES post-processing.

            Please carefully review the changes and finally merge them into your

      # Delete all the curation branches
      - run: |
          for BRANCH in $(git ls-remote origin 'refs/heads/hermes/curate-*' | cut -f2 | cut -d'/' -f'3-'); do
            git push origin --delete "$BRANCH"
          done
          

  hermes-cleanup:
    name: Cleanup aborted curation branches
    if: github.event.pull_request.merged == false && startsWith( github.base_ref , 'hermes/curate-')

    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow creation of new branches
      pull-requests: write # Postprocessing should be able to create a pull request with changes

    steps:
      - uses: actions/checkout@v3
      # Delete all the curation branches
      - run: |
          for BRANCH in $(git ls-remote origin 'refs/heads/hermes/curate-*' | cut -f2 | cut -d'/' -f'3-'); do
            git push origin --delete "$BRANCH"
          done