name: Software Publication

on:
  push:

jobs:
  hermes:
    name: HERMES
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install git+https://github.com/hermes-hmc/workflow.git
      - run: hermes
      - run: hermes deposit